### ISSUE TITLE
TypeError when using ctrl+alt+o 

### ISSUE THREAD

**Issue by q-erty** [gerardroche/sublime-sesame#10]
I just installed sesame on sublime text 3176. Trying to open a new project, nothing happens and I instead see the following error in my sublime text console:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1036, in run_
    return self.run()
  File "/Users/<me>/Library/Application Support/Sublime Text 3/Installed Packages/Sesame.sublime-package/plugin.py", line 59, in run
  File "/Users/<me>/Library/Application Support/Sublime Text 3/Installed Packages/Sesame.sublime-package/plugin.py", line 160, in _find_folders
TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Comment by q-erty** [comment]
I was able to fix this by providing `sesame.depth` in my user settings file.
